# NAME OF THE WORKFLOW AS IT WILL APPEAR IN THE ACTIONS TAB

name: PYTHON APPLICATION


# EVENTS THAT WILL TRIGGER THIS WORKFLOW

on:
  push:                  # WHENEVER YOU PUSH TO MAIN BRANCH
    branches: [ "main" ]
  pull_request:          # OR WHEN A PULL REQUEST IS MADE TO MAIN
    branches: [ "main" ]

# DEFINE THE JOBS TO BE RUN

jobs:
  build:
    runs-on: ubuntu-latest  # SPECIFY THE OPERATING SYSTEM

    steps:
    
    # STEP 1: CHECK OUT THE REPOSITORY CODE

    - uses: actions/checkout@v4

    # STEP 2: SET UP PYTHON VERSION 3.10

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # STEP 3: UPGRADE PIP (OPTIONAL, SAFE DEFAULT)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    # STEP 4: RUN lab2.py AND PRINT TIMING RESULTS

    - name: Run lab2.py and measure timing
      run: |
        python lab2.py
